name: Release to EC2 Instance 

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy into EC2 instance and pull the latest changes
      run: |
          cd /home/ubuntu/linux
          docker-compose -f /home/ubuntu/linux/docker-compose.yml pull
          docker-compose -f /home/ubuntu/linux/docker-compose.yml up -d
